import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import LoginBtn from "./LoginBtn.js"
import AuthProvider from "./AuthProvider.js"
import { authOptions } from "./api/auth/[...nextauth]/route.js"
import { getServerSession } from "next-auth"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // getServerSession으로 세션 정보 가져오기
  const session = await getServerSession(authOptions)

  if (session) {
    console.log('세션출력: ' + JSON.stringify(session))
  }

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider session={session}>
          <div className="navbar">
            <Link href="/" className="logo">BSSM board</Link>
            <Link href="/list">글목록</Link>
            <Link href="/write">글쓰기</Link>
            <LoginBtn session={session} />
          </div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
